apiVersion: v1
kind: ResourceQuota
metadata:
  name: karmada-resource-quota
  namespace: karmada-system
spec:
  hard:
    pods: 1000
  scopeSelector:
    matchExpressions:
    - operator: In
      scopeName: PriorityClass
      values:
      - system-node-critical
      - system-cluster-critical